[package]
name = "http"
version = "0.1.0"
authors = ["CJP10 <connor.peticca@logdna.com>"]
edition = "2018"

[dependencies]
#local
metrics = { package = "metrics", path = "../metrics" }
#http
logdna-client = "0.1"
#io
tokio = "0.1"
#utils
log = "0.4"
crossbeam = "0.7"
uuid = { version = "0.7", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
quick-error = "1"

[dev-dependencies]
rand = "0.7"
num_cpus = "1"
