[package]
name = "journald"
version = "0.1.0"
authors = ["jakedipity <jacob.hull@logdna.com>"]
edition = "2018"

[dependencies]
#local
http = { package = "http", path = "../http" }
source = { package = "source", path = "../source" }

systemd = { package = "systemd", version = "~0.4", optional = true }
log = "0.4"
chrono = "0.4"

[features]
default = []
use_systemd = ["systemd"]
