[package]
name = "fs"
version = "0.1.0"
authors = ["CJP10 <connor.peticca@logdna.com>"]
edition = "2018"

[dependencies]
#local
http = { package = "http", path = "../http" }
metrics = { package = "metrics", path = "../metrics" }
source = { package = "source", path = "../source" }

#io
inotify = "0.8"
#error
quick-error = "1"
#utils
pcre2 = "0.2"
globber = "0.1.2"
hashbrown = "0.6"
#logging
log = "0.4"
env_logger = "0.6"
lazy_static = "1.4.0"

[dev-dependencies]
tempdir = "0.3"
