[package]
name = "k8s"
version = "0.1.0"
authors = ["CJP10 <connor.peticca@logdna.com>"]
edition = "2018"

[dependencies]
#local
middleware = { package = "middleware", path = "../middleware" }
http = { package = "http", path = "../http" }
metrics = { package = "metrics", path = "../metrics" }

crossbeam = "0.7"
inotify = "0.7"
regex = "1"
lazy_static = "1"
log = "0.4"
quick-error = "1"
parking_lot = "0.9"
kube = { version = "0.16", features = ["openapi"] }
serde_json = "1"